import { Doctor, Appointment, TimeSlot } from '@/types'

export const DOCTORS: Doctor[] = [
  {
    id: 'd1',
    name: 'Dr. Aisha Rahman',
    specialty: 'Cardiologist',
    rating: 4.9,
    reviewCount: 312,
    fee: 45,
    available: true,
    nextSlot: 'Today, 2:00 PM',
    avatar: 'AR',
    tags: ['Heart health', 'Hypertension', 'ECG'],
    experience: 12,
    bio: 'Board-certified cardiologist with 12 years of experience treating heart disease, hypertension, and arrhythmias. Fellow of the American College of Cardiology.',
  },
  {
    id: 'd2',
    name: 'Dr. Usman Tariq',
    specialty: 'Dermatologist',
    rating: 4.8,
    reviewCount: 198,
    fee: 38,
    available: true,
    nextSlot: 'Today, 3:30 PM',
    avatar: 'UT',
    tags: ['Acne', 'Eczema', 'Skin cancer'],
    experience: 8,
    bio: 'Specialist in medical and cosmetic dermatology. Expert in acne, eczema, psoriasis, and skin cancer screenings.',
  },
  {
    id: 'd3',
    name: 'Dr. Sana Mirza',
    specialty: 'Psychiatrist',
    rating: 4.9,
    reviewCount: 427,
    fee: 60,
    available: true,
    nextSlot: 'Today, 4:00 PM',
    avatar: 'SM',
    tags: ['Anxiety', 'Depression', 'Therapy'],
    experience: 15,
    bio: 'Psychiatrist specializing in anxiety, depression, and trauma. Uses evidence-based CBT and mindfulness approaches.',
  },
  {
    id: 'd4',
    name: 'Dr. James Okafor',
    specialty: 'General Physician',
    rating: 4.7,
    reviewCount: 561,
    fee: 25,
    available: true,
    nextSlot: 'Available now',
    avatar: 'JO',
    tags: ['Fever', 'Prescriptions', 'Check-ups'],
    experience: 10,
    bio: 'Experienced general practitioner handling a wide range of acute and chronic conditions. Available for same-day consultations.',
  },
  {
    id: 'd5',
    name: 'Dr. Priya Sharma',
    specialty: 'Paediatrician',
    rating: 4.9,
    reviewCount: 284,
    fee: 35,
    available: true,
    nextSlot: 'Tomorrow, 9:00 AM',
    avatar: 'PS',
    tags: ['Child health', 'Vaccinations', 'Growth'],
    experience: 9,
    bio: 'Dedicated paediatrician caring for newborns through adolescents. Specialises in developmental health and childhood illnesses.',
  },
  {
    id: 'd6',
    name: 'Dr. Ahmed Al-Farsi',
    specialty: 'Neurologist',
    rating: 4.8,
    reviewCount: 176,
    fee: 55,
    available: false,
    nextSlot: 'Tomorrow, 11:00 AM',
    avatar: 'AA',
    tags: ['Migraines', 'Epilepsy', 'MS'],
    experience: 14,
    bio: 'Neurologist with expertise in headaches, epilepsy, and multiple sclerosis. Trained at Johns Hopkins.',
  },
]

export const TIME_SLOTS: TimeSlot[] = [
  { time: '9:00 AM', available: true },
  { time: '9:30 AM', available: false },
  { time: '10:00 AM', available: true },
  { time: '10:30 AM', available: true },
  { time: '11:00 AM', available: false },
  { time: '11:30 AM', available: true },
  { time: '1:00 PM', available: false },
  { time: '1:30 PM', available: true },
  { time: '2:00 PM', available: true },
  { time: '3:00 PM', available: true },
  { time: '3:30 PM', available: false },
  { time: '4:00 PM', available: true },
]

export const MOCK_APPOINTMENTS: Appointment[] = [
  {
    id: 'a1',
    doctorId: 'd1',
    doctorName: 'Dr. Aisha Rahman',
    patientName: 'Sara Ahmed',
    patientEmail: 'sara@example.com',
    date: '2026-09-20',
    time: '2:00 PM',
    status: 'upcoming',
    type: 'video',
    fee: 45,
    specialty: 'Cardiologist',
    symptoms: 'Chest tightness and occasional palpitations',
  },
  {
    id: 'a2',
    doctorId: 'd3',
    doctorName: 'Dr. Sana Mirza',
    patientName: 'Sara Ahmed',
    patientEmail: 'sara@example.com',
    date: '2026-09-15',
    time: '4:00 PM',
    status: 'completed',
    type: 'video',
    fee: 60,
    specialty: 'Psychiatrist',
  },
  {
    id: 'a3',
    doctorId: 'd2',
    doctorName: 'Dr. Usman Tariq',
    patientName: 'Sara Ahmed',
    patientEmail: 'sara@example.com',
    date: '2026-09-25',
    time: '3:30 PM',
    status: 'upcoming',
    type: 'video',
    fee: 38,
    specialty: 'Dermatologist',
    symptoms: 'Persistent rash on forearms',
  },
]

export const DOCTOR_APPOINTMENTS: Appointment[] = [
  {
    id: 'da1',
    doctorId: 'd1',
    doctorName: 'Dr. Aisha Rahman',
    patientName: 'Sara Ahmed',
    patientEmail: 'sara@example.com',
    date: '2026-09-20',
    time: '2:00 PM',
    status: 'upcoming',
    type: 'video',
    fee: 45,
    specialty: 'Cardiologist',
    symptoms: 'Chest tightness and occasional palpitations',
  },
  {
    id: 'da2',
    doctorId: 'd1',
    doctorName: 'Dr. Aisha Rahman',
    patientName: 'Ravi Joshi',
    patientEmail: 'ravi@example.com',
    date: '2026-09-20',
    time: '3:00 PM',
    status: 'upcoming',
    type: 'video',
    fee: 45,
    specialty: 'Cardiologist',
    symptoms: 'High blood pressure readings at home',
  },
  {
    id: 'da3',
    doctorId: 'd1',
    doctorName: 'Dr. Aisha Rahman',
    patientName: 'Maria Kowalski',
    patientEmail: 'maria@example.com',
    date: '2026-09-18',
    time: '10:00 AM',
    status: 'completed',
    type: 'video',
    fee: 45,
    specialty: 'Cardiologist',
  },
]
